language: ruby
rvm:
- ruby-2.0.0
env:
- DB=postgresql
before_script:
- bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
script:
- bundle exec rspec spec
- bundle exec cucumber
deploy:
  provider: heroku
  api_key:
    secure: UuZpSRW23bGKReDfucjIyzfQwy/pGCt11xZoFWG+XSjuJHZkyl7mpjeG0bVj/XWyp4engOSDIxoJ+/8czHmadr2kyGeFLgJJLGkub3mHwQ7GFXP1GYQafxDcXTzm2ZuPj29Z6oIjEQF+CNtciWZrK7ROnEk1ISoPlIEQp/ZxbeA=
  app:
  on:
    repo:
    branch:
  run: "rake db:migrate"
